### ISSUE TITLE
Update J3 February meeting update

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fortran-lang.github.io#1]
@certik When you have some time, can you please post your J3 February meeting update in this file:

https://github.com/fortran-lang/fortran-lang.github.io/blob/master/_posts/2020-02-25-J3-february-meeting.md

**Comment by certik** [comment]
Yes! Thank you. I'll do it very soon.

**Comment by certik** [comment]
This has been fixed in #29, #30 and #42. The result is visible at:

https://fortran-lang.org/newsletter/2020/02/28/J3-february-meeting/
