### ISSUE TITLE
Write down criteria how to include a package

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.github.io#20]
We should also setup criteria how to include a package there --- right now the criterion I think was at least 29 stars at GitHub and Fortran as the majority language (as determined by GitHub). I would be for lowering the number of stars, for example if we lower to 15, then one of my other 100% Fortran project would qualify: https://github.com/certik/hfsolver :), what is nice about this one is that it has all kinds of very good computational routines that could be useful for others. But if we lower the number of stars, then I want to do it in a systematic way, I want to see every single GitHub project included. I think we achieved it with the > 29 stars.

**Comment by LKedward** [comment]
Yes I think we need criteria - however having now been through a large list of projects I don't find number of stars to be a very good indicator of project quality or utility.
I find they are much more like social media 'likes' and, as I think you've mentioned @certik, they are skewed towards projects which have been online for longer.

I think more objective criteria should be used to include projects which importantly __will allow new projects to gain good exposure and momentum__. Such objective criteria could include:

- Project does not appear to be archived/abandoned
- Project includes open source license
- Project has a README clearly stating project purpose, dependencies and build process
- Project source can be browsed and cloned without registration
- Project permits issues/tickets to be raised
- Project has some form of documentation (however basic)

A possible idea is to have a stricter set of criteria which earn the project a green 'Verified' flag in the package index and a higher ranking:

- Project contains complete documentation
- Project contains tests
- Project follows some standard best practices for portability

**Comment by milancurcic** [comment]
I don't think we should use GitHub stars as a criterion. It was okay for the first step but we need something better now. I think we all agree that the number of GitHub stars is not a measure of relevence of a package.

I also don't think we should include every GitHub Fortran project. Many repos could fall in that are either unusable or semi-usable, or they're a slight modification of another project.

As you say, we need to decide what makes a package relevant enough. I think some requirements should be:

* Pure Fortran or mixed-language project where Fortran is the majority of the code (or > than some % of the code). This is somewhat arbitrary;
* Either installable by fpm (in the future) or includes install instructions in the repo;
* Unique: We shouldn't include packages that are a slight modification of an existing package. Including them could create confusion for the end user.

My guess is that based on these criteria, most packages that one would care submitting would be acceptable.

**Comment by milancurcic** [comment]
I agree with most ideas by @LKedward, except these:

> Project does not appear to be archived/abandoned

I think we would be amiss to not include some mature legacy projects that aren't actively maintained. I can't think of any from the top of my head, but I'd bet there are.

> Project permits issues/tickets to be raised

This one may be too restrictive as it assumes a development platform. It would disqualify archived packages which I think may be important to list.

But of course, I'm yet to provide examples of worthwhile archived projects.

**Comment by certik** [comment]
The proposed criteria from @LKedward and @milancurcic seem ok with me.

I would like some criterion to exclude projects that literally just started and have no users and are not yet clear that they would be a good community project. As an example of such a project would be https://github.com/certik/allocate. I know that this project doesn't satisfy the other criteria either (e.g., doesn't have a README).

How about an additional criterion such as having at least 5 GitHub stars? A really low bar, but it would exclude some personal test projects such as the one I linked above.

**Comment by certik** [comment]
An in addition, after we write down the criteria, I would say that it has to get at least 3 positive reviews from the fortran-lang community. That way we will simply judge each project on a case by case basis, and requiring 3 reviews should guarantee that we are fair.

**Comment by LKedward** [comment]
I agree with all these points

**Comment by certik** [comment]
@LKedward if you have time, do you want to submit a PR with the document that has these rules?

**Comment by LKedward** [comment]
@certik yep I can do that.

**Comment by certik** [comment]
This was fixed in #26.
