### ISSUE TITLE
addition to the list scientific codes

### ISSUE THREAD

**Issue by p-costa** [fortran-lang/fortran-lang.github.io#21]
would it be possible to add CaNS to the list of scientific codes?

the repo on github: https://github.com/p-costa/CaNS

**Comment by LKedward** [comment]
This code looks good, I don't think there'll be an opposition to adding it.

Are you happy with the following entry:
```
name: Canonical Navier Stokes (CaNS)
description: A code for fast, massively-parallel direct numerical simulations (DNS) of canonical flows
License: MIT
```

Can you suggest some tags to use for indexing?
Do you have a version number or plan to release a version on github?

**Comment by milancurcic** [comment]
@p-costa very nice project!

@LKedward @certik we should design a PR template with a checklist for these submissions.

**Comment by p-costa** [comment]
Thanks @LKedward :). The description is perfect. I would just change the name to just `name: CaNS`.

In terms of tags, I can suggest those of the GitHub repo: 

`fluid-dynamics`
`fluid-simulation`
`computational-fluid-dynamics`
`turbulence`
`high-performance-computing`
`cfd`

I do not have a release version on GitHub, and I was not planning to have it for the being; hope that is fine!

**Comment by certik** [comment]
@p-costa thanks! We missed this project I think in our initial list.

We are still figuring out the detailed criteria in #20, but I think you are satisfying them, so you have my +1.

**Comment by LKedward** [comment]
Cheers @p-costa, that's great! Will put together the PR.
