### ISSUE TITLE
Should we list g95 in open source compilers?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fortran-lang.github.io#28]
http://g95.org/

I'm torn. :)

On one side, I used this compiler briefly over 10 years ago and it's dear to me. "It's free crunch time" is an awesome tagline. Despite what its name implies, this compiler supports [coarrays](http://www.g95.org/coarray.shtml) out of the box, at least to some capacity. Its [status page](http://www.g95.org/g95_status.shtml) has a long list of packages that work with g95.

On the other side, it looks like the project is not developed any more. The most recent update on the site that I can find is from 2013.

**Comment by jacobwilliams** [comment]
I would say no. It’s defunct. I know people still use it but people still use g77 too. Best not to encourage that.

**Comment by milancurcic** [comment]
Indeed. From looking at the source, it seems that g95 was meant to be included as the Fortran frontend of GCC. I guess it continued as its own project once gfortran was released.

**Comment by certik** [comment]
I vote no. I would only list actively maintained compilers. Otherwise we have to list every old F77 and other commercial compilers. Every old compiler can be used in principle. But the purpose of the page is to list compilers that are maintained today.

**Comment by milancurcic** [comment]
The opinion is unanimous on this one, so I will close it.
