### ISSUE TITLE
Make the favicon F white inside

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.github.io#44]
Currently this is how the https://fortran-lang.org/ page looks in a Tab that is not active:

![Screenshot from 2020-04-30 09-59-35](https://user-images.githubusercontent.com/20568/80732330-640f3800-8ac9-11ea-80eb-70627e406f0a.png)

The F is really hard to read. We should make the F inside the purple box white. That way it should be nicely visible.

**Comment by certik** [comment]
It's this file that has to be fixed: https://github.com/fortran-lang/fortran-lang.github.io/blob/837383d01152ff8fdf5412228fca6bee8c09781f/favicon.ico

**Comment by certik** [comment]
Thanks @jacobwilliams. I thought you did too, but for some reason it still is transparent on the website. Not sure where the problem is.

**Comment by LKedward** [comment]
@certik could your browser be caching the old icon?
It doesn't appear transparent here: <https://fortran-lang.org/favicon.ico>

**Comment by certik** [comment]
@LKedward I don't know. Can you send a screenshot how it looks like in an inactive Tab for you?

I would like the corners to be transparent, but the F inside to be white.

**Comment by LKedward** [comment]
![fortran-lang](https://user-images.githubusercontent.com/26024234/80735567-cf2c2f00-8b08-11ea-947f-c22af5c19c00.PNG)
![fortran-lang_2](https://user-images.githubusercontent.com/26024234/80735570-cfc4c580-8b08-11ea-9a41-94cf70d60b9d.PNG)

**Comment by certik** [comment]
Ok, maybe it is cached. Here is how the fortran-lang.org tab looks like now:

Inactive:

![Screenshot from 2020-04-30 10-33-04](https://user-images.githubusercontent.com/20568/80735534-177a2b80-8ace-11ea-85f4-adddf7e22156.png)

Active:

![Screenshot from 2020-04-30 10-34-13](https://user-images.githubusercontent.com/20568/80735600-29f46500-8ace-11ea-99a8-c2dd172cdde7.png)

In both cases, the corners are transparent and the F is white, as I would like it.

So maybe it's already fixed and it was just my browser that cached the old icon? Can others confirm that what they see is exactly what I posted in this comment?

**Comment by certik** [comment]
I am going to close this. I think it is fixed.

**Comment by ivan-pi** [comment]
Just noticed this issue now. After clicking "Clear recent history" in my browser and marking the *cache* checkbox, the favicon is displayed correctly. :+1:
