### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fortran-lang.github.io#47]
Thank you @certik for starting the [fortran-lang mailinglist](https://groups.io/g/fortran-lang).

For everybody else, please see Group Email Addresses on that page for details.

Specifically, we should have a subscription link on the website.

I think a good place is on the landing page in the "Join us" section, such that we have, in this order:

* Subscribe to the [mailing list](https://groups.io/g/fortran-lang)
* Follow us on Twitter
* Contribute on GitHub
* Ask about usage on Stack Exchange

In addition, it should also be in the sidebar on the [news page](https://fortran-lang.org/news/)

@certik @LKedward Let me know what you think and I can follow up with a PR.

**Comment by certik** [comment]
I think that looks good. Can you submit a PR? Let's get it done, then we can refine later.
