### ISSUE TITLE
Add Discourse badge to the landing page

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fortran-lang.github.io#52]
We now have a [Discourse](https://fortran-lang.discourse.group/) instance. Please join and try it out.

The website should have a hyperlinked Discourse badge that would allow people who visit the site to discover Discourse. We have an obvious place for this, where we list the mailing list, Twitter, and so on.

**Comment by certik** [comment]
Thanks for setting it up. For inspiration, here is how Rust and Julia do discourse:

https://users.rust-lang.org/
https://discourse.julialang.org/
