### ISSUE TITLE
F18 information outdated

### ISSUE THREAD

**Issue by ivan-pi** [fortran-lang/fortran-lang.github.io#6]
It seems that the [F18](https://github.com/flang-compiler/f18) front-end branch has been accepted as the brand new [flang](https://github.com/llvm/llvm-project/tree/master/flang/) and is part of the official LLVM project. The former flang compiler still exists [here](https://github.com/flang-compiler/flang).

I can take a shot at updating the page in the upcoming days, if no one else does it first.

**Comment by milancurcic** [comment]
Absolutely, let's fix it!

**Comment by certik** [comment]
Yes, I think it should be just called Flang.

**Comment by LKedward** [comment]
@ivan-pi I believe this was fixed with #16 and can be closed?

**Comment by ivan-pi** [comment]
Sure. Great work!
